### ISSUE TITLE
Some issues when using Easy API

### ISSUE THREAD

**Issue by lbertoncello** [open-wa/wa-automate-nodejs#1495]
I'm using Easy API running on docker to send messages. Sometimes I got the following error on Easy API:

```
middleware -> error Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
    at eval (eval at <anonymous> (:1:27), <anonymous>:1:31056)
    at X (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:307039)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:306620)
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
```
Furthermore, I got the following response on the request:

```
{
    "success": false,
    "error": {}
}
```

The strangest thing about this is that the message is sent, despite the errors triggered and, for some reason, it's sent twice. I did tests by sending messages to my personal number and I realized that this seems to happen only when it is the first message I send to the contact. I use a license key, so I think this is not the expected behavior.

**DEBUG INFO**

```
Debug Info {
  WA_VERSION: '2.2108.8',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.9.6',
  BROWSER_VERSION: 'HeadlessChrome/90.0.4427.0',
  OS: 'Linux 4.4'
}

**Comment by smashah** [comment]
@lbertoncello can you share the CLI command you use to start the process, please.

If you are setting webhooks, then can you try without setting any webhooks and see if this problem still happens.

Thanks

**Comment by lbertoncello** [comment]
> @lbertoncello can you share the CLI command you use to start the process, please.

```
npx @open-wa/wa-automate --in-docker --api-host $API_HOST -p 3000 -k $API_KEY -w $API_WEBHOOK --qr-timeout 0 --qr-log-skip --disable-spins --popup -l $API_LICENSE
```

> If you are setting webhooks, then can you try without setting any webhooks and see if this problem still happens.

Okay, I'm going to test it and give you feedback.

**Comment by lbertoncello** [comment]
> If you are setting webhooks, then can you try without setting any webhooks and see if this problem still happens.

The issue persists even without a webhook.

**Comment by smashah** [comment]
Thanks for checking @lbertoncello can you do me a favour and update the error logs in the first comment because the WhatsApp version has been updated now.

**Comment by lbertoncello** [comment]
> Thanks for checking @lbertoncello can you do me a favour and update the error logs in the first comment because the WhatsApp version has been updated now.

Do you mean the debug info?

**Comment by smashah** [comment]
I mean this:

```bash
middleware -> error Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
    at eval (eval at <anonymous> (:1:27), <anonymous>:1:34416)
    at X (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:307039)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:306620)
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/app/
```

**Comment by lbertoncello** [comment]
> I mean this:
> 
> ```shell
> middleware -> error Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
>     at eval (eval at <anonymous> (:1:27), <anonymous>:1:34416)
>     at X (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:307039)
>     at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:306620)
>     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async ExecutionContext.evaluate (/app/
> ```

I didn't understand. Is there a new release that correct this error?

**Comment by lbertoncello** [comment]
> No, but there is a new version of WA web which would update the contents of this error.
> 
> Edit: sorry I closed the issue by accident

OK, I will do this

**Comment by lbertoncello** [comment]
@smashah It's done, I've updated the log

```
middleware -> error Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
    at eval (eval at <anonymous> (:1:27), <anonymous>:1:31056)
    at X (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:307039)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:306620)
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.9.7](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.6...3.9.7) (2021-03-20)

- build(deps): bump open from 8.0.2 to 8.0.3 [`#1499`](https://github.com/open-wa/wa-automate-nodejs/pull/1499)
- build(deps-dev): bump @typescript-eslint/parser from 4.17.0 to 4.18.0 [`#1489`](https://github.com/open-wa/wa-automate-nodejs/pull/1489)
- build(deps): bump puppeteer-extra-plugin-devtools from 2.2.16 to 2.2.17 [`#1487`](https://github.com/open-wa/wa-automate-nodejs/pull/1487)
- build(deps-dev): bump @types/node from 14.14.34 to 14.14.35 [`#1488`](https://github.com/open-wa/wa-automate-nodejs/pull/1488)
- build(deps-dev): bump @typescript-eslint/eslint-plugin from 4.17.0 to 4.18.0 [`#1491`](https://github.com/open-wa/wa-automate-nodejs/pull/1491)
- build(deps): bump uuid-apikey from 1.5.1 to 1.5.2 [`#1490`](https://github.com/open-wa/wa-automate-nodejs/pull/1490)
- Release 3.9.7 [`1878c1f`](https://github.com/open-wa/wa-automate-nodejs/commit/1878c1f25cea89e5c99f4761fdd4f637c9372071)
- ♻️  refactor initializer #1493 [`c85786a`](https://github.com/open-wa/wa-automate-nodejs/commit/c85786a6b31ae50f53672ff43d11c229459ea27c)
- 🐛  updated `client.refresh` #1493 [`cca2599`](https://github.com/open-wa/wa-automate-nodejs/commit/cca2599ec581701f9651982c4f40990e0f05c25f)
- ✨ feat: `sendMp4AsSticker` can now take `messageId` parameter for reply video stickers [insiders] [`22a7a0a`](https://github.com/open-wa/wa-automate-nodejs/commit/22a7a0ab3fe177cbf2a492e1b9909e73824521b1)
- ♻️  refactor out license fetcher [`b3533b3`](https://github.com/open-wa/wa-automate-nodejs/commit/b3533b3f14c5c296ed68ab0f415956697b3b9092)
- ✨ implemented timer on `client.refresh()` and preload license #1493 [`cbd9a53`](https://github.com/open-wa/wa-automate-nodejs/commit/cbd9a531561e8bbba806e52017fb607e120bc09f)
- 🐛  CLI errors now also show `error.message` [`2df7ae8`](https://github.com/open-wa/wa-automate-nodejs/commit/2df7ae83c4989a63ddba0755e3723453b70b3b19)
- 🐛  fix bug where no-path `--api-host` causes double slash in api-docs/oas [`d0e4cca`](https://github.com/open-wa/wa-automate-nodejs/commit/d0e4ccae6e509a0f7d76dea03cf897b4c27cb289)
- 🥚  patches update [`3b1b5fb`](https://github.com/open-wa/wa-automate-nodejs/commit/3b1b5fb006d4f1b8448a350c86fc537fcadaa7fc)
- 🔧 (dev) update tsconfig from `ES5` to `ES2015` [`d1b24fc`](https://github.com/open-wa/wa-automate-nodejs/commit/d1b24fce63240ad4cc6621cf42b17b257039f561)
- 🥚  #1495 #1498 [`6703edd`](https://github.com/open-wa/wa-automate-nodejs/commit/6703eddcb31eba37f2ecc0b0398dd9af5ed03196)
- 🥚  patches update [`5343705`](https://github.com/open-wa/wa-automate-nodejs/commit/53437050db0853a63846dfc1cdbd1628041b017a)

**Comment by smashah** [comment]
@lbertoncello can you update and try again. Hopefully the issues are fixed now.

**Comment by smashah** [comment]
@lbertoncello closing for now. feel free to bump if there are still problems or message me on discord. thanks

**Comment by lbertoncello** [comment]
@smashah I've tested the version 3.9.13 today. I'm still facing this issue

**Comment by smashah** [comment]
@lbertoncello can you dm me on discord please

**Comment by lbertoncello** [comment]
> @lbertoncello can you dm me on discord please

Sure!

**Comment by lbertoncello** [comment]
> @lbertoncello can you dm me on discord please

@smashah  Where can I find your user on discord?

**Comment by smashah** [comment]
@lbertoncello please click the discord badge in the readme to join the channel and mention this issue.
