### ISSUE TITLE
Failed to run npm install

### ISSUE THREAD

**Issue by wilianwrech** [open-wa/wa-automate-nodejs#1629]
**Describe the bug**
Running npm i --save @open-wa/wa-automate@latest leads to an error.

**Steps to Reproduce**
1. run `npm init` in an empty folder 
2. run `npm i --save @open-wa/wa-automate@latest`

**Expected behavior**
To installation work

**DEBUG INFO**

**Screenshots**

**Host (please complete the following information):**

**Additional context**
```
PS C:\Repositorio\wa-automate> npm i --save @open-wa/wa-automate@latest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> puppeteer@9.0.0 install C:\Repositorio\wa-automate\node_modules\puppeteer
> node install.js

Downloading Chromium r869685 - 166.1 Mb [====================] 100% 0.0s
Chromium (869685) downloaded to C:\Repositorio\wa-automate\node_modules\puppeteer\.local-chromium\win64-869685

> @open-wa/wa-automate@3.11.6 postinstall C:\Repositorio\wa-automate\node_modules\@open-wa\wa-automate
> patch-package

patch-package 6.4.7
Applying patches...
Error: Patch file found for package swagger-stats which is not present at node_modules/swagger-stats
Error: Patch file found for package typedoc-plugin-pages which is not present at node_modules/typedoc-plugin-pages
---
patch-package finished with 2 error(s).
npm WARN @open-wa/wa-automate@3.11.6 requires a peer of fluent-ffmpeg@^2.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN @open-wa/wa-automate@3.11.6 requires a peer of sharp@^0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN swagger-stats@0.99.1 requires a peer of prom-client@>= 10 <= 13 but none is installed. You must install peer dependencies yourself.
```

Node JS version: 14.16.1

**Comment by smashah** [comment]
@wilianwrech you should be able to just ignore these errors

**Comment by smashah** [comment]
I just tried it on a fresh VM and despite the warnings, the install is successful and you can move forward to using the library:

![image](https://user-images.githubusercontent.com/5903821/116745675-54d00c80-a9f3-11eb-802f-5acf9a67d330.png)

**Comment by wilianwrech** [comment]
I tried using `--ignore-scripts`, but more errors happened when starting my project, I assumed it was because of the installation.

```
node_modules/@open-wa/wa-automate/dist/controllers/events.d.ts:2:22 - error TS7016: Could not find a declaration file for module 'spinnies'. 'C:/Repositorio/wa-automate/node_modules/spinnies/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/spinnies` if it exists or add a new declaration (.d.ts) file containing `declare module 'spinnies';`

2 import Spinnies from "spinnies";
                       ~~~~~~~~~~

node_modules/@open-wa/wa-automate/dist/structures/MessageCollector.d.ts:40:5 - error TS2416: Property 'dispose' in type 'MessageCollector' is not assignable to the same property in base type 'Collector'.
  Type '(message: Message) => `false_${number}-${number}@g.us_${string}` | `false_${number}@c.us_${string}` | `true_${number}-${number}@g.us_${string}` | `true_${number}@c.us_${string}` | null' is not assignable to type '(...args: any[]) => string'.
    Type '`false_${number}-${number}@g.us_${string}` | `false_${number}@c.us_${string}` | `true_${number}-${number}@g.us_${string}` | `true_${number}@c.us_${string}` | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

40     dispose(message: Message): MessageId | null;
       ~~~~~~~

node_modules/@open-wa/wa-automate/dist/structures/MessageCollector.d.ts:46:5 - error TS2416: Property 'endReason' in type 'MessageCollector' is not assignable to the same property in base type 'Collector'.
  Type '() => string | null' is not assignable to type '(...args: any[]) => string'.
    Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

46     endReason(): string | null;
```
My dependencies: 
```
  "dependencies": {
    "@open-wa/wa-automate": "^3.11.6",
    "cors": "^2.8.5",
    "debug": "^4.3.1",
    "express": "^4.17.1",
    "express-winston": "^4.1.0",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "@types/cors": "^2.8.10",
    "@types/debug": "^4.1.5",
    "@types/express": "^4.17.11",
    "source-map-support": "^0.5.19",
    "tslint": "^6.1.3",
    "typescript": "^4.2.4"
  }
```

**Comment by smashah** [comment]
this should be fixed in the latest version 

thanks

**Comment by MBayoumi** [comment]
this issue still exist

 `node_modules/@open-wa/wa-automate/dist/controllers/events.d.ts:2:22 - error TS7016: Could not find a declaration file for module 'spinnies'.  implicitly has an 'any' type.
  Try `npm i --save-dev @types/spinnies` if it exists or add a new declaration (.d.ts) file containing `declare module 'spinnies';`

2 import Spinnies from "spinnies";`

**Comment by smashah** [comment]
@MBayoumi can you confirm that this is set to true in your ts-config?

https://www.typescriptlang.org/tsconfig/skipLibCheck.html

**Comment by MBayoumi** [comment]
my tsconfig.json 
`{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true
  }
}` 

after deleting node modules and dist and using --ignore-scripts it works 

thanks @smashah
