### ISSUE TITLE
Uncaught TypeError: stick.sendToChat is not a function

### ISSUE THREAD

**Issue by vphelipe** [open-wa/wa-automate-nodejs#2438]
With the new update of whatsapp web it is now no longer possible to send Sticker. Problem is on the line:

https://github.com/open-wa/wa-automate-nodejs/blob/f97ca0ba7d3951721627068a9dbf9dfd5b081468/src/lib/wapi.js#L2003

**Comment by smashah** [comment]
Fixed in patches

**Comment by klujanrosas** [comment]
@smashah I'm sorry to add noise to this Issue, I checked out **patches** and there's no reference whatsoever to this issue (which is still happening, for me at least). Would you be so kind to point me in the right direction?

**Comment by smashah** [comment]
@klujanrosas please fill the issue template if this is still happening to you with reproducable steps
