### ISSUE TITLE
cli: when a new chat is initiated using chatwoot response open a new conversation

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2570]
Steps to reproduce:

1. Initiate a new conversation using ChatWoot selecting contact and a "open-wa inbox channel"
2. Respond on WhatsApp to received message
3. Received message bt ChatWoot doesn't persist on initiated convesartion (step 1) and a new one is created

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.32.15](https://github.com/open-wa/wa-automate-nodejs/compare/4.32.14...4.32.15) (2022-03-18)

- Release 4.32.15 [`d4c849e`](https://github.com/open-wa/wa-automate-nodejs/commit/d4c849ec8fe352c796bcca3be51481f06bf3a8a0)
- 🩹  fix: #2570 [`4e98701`](https://github.com/open-wa/wa-automate-nodejs/commit/4e98701dbf9e0ffd941eee5a0e09881553717ca4)
- updated types-only package [`d11ad82`](https://github.com/open-wa/wa-automate-nodejs/commit/d11ad82730660b728c0204349ae5f3f91c5becd0)

**Comment by smashah** [comment]
@silvaartur should be fixed with latest version

**Comment by silvaartur** [comment]
Problem persists. Two subsequent messages generate two conversations as below:

<img width="488" alt="Captura de Tela 2022-04-04 às 23 43 58" src="https://user-images.githubusercontent.com/12688324/161669302-3375399d-cb12-4553-a178-f2d081367dfc.png">
