### ISSUE TITLE
setChatEphemeral not work in group

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2666]
only work on private chat

**Comment by smashah** [comment]
fixed. restart and try again.

**Comment by dandyraka** [comment]
> fixed. restart and try again.

@smashah still not work
![image](https://user-images.githubusercontent.com/18587059/164310817-a1ece453-73a1-4669-bcc6-2eb59c3e1eb2.jpeg)
