### ISSUE TITLE
Fail when send a link sendLinkWithAutoPreview

### ISSUE THREAD

**Issue by paulocorcino** [open-wa/wa-automate-nodejs#916]
**Describe the bug**
All method work normally, but, after last update (I'm use 2.0.29), when I send a link (link with auto preview), the contact receive the link, but my application receive a timeout and the wa-automate stop of send message, with this I need restart instance to return work. Some days ago that method was working normally with 1.9.XXX versions.

**create() code**
This is the code you use to create the client. e.g
```javascript
WA_CLIENT.CONNECTION.sendLinkWithAutoPreview(processData.chatId, BODY['link'], BODY['text']).then(function(Chat){
							self.json({status:true, id: null, data: Chat});
						});
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2041.6',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '2.0.29',
  BROWSER_VERSION: 'Chrome/85.0.4183.121'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: WINDOWS SERVER 2012 R2

**Additional context**

**Comment by smashah** [comment]
@paulocorcino I'm unable to reproduce your error. Can you provide example params where this issue happens? Everything seems to be working fine on this end. Can you try again and see if it is still happening?

**Comment by paulocorcino** [comment]
@smashah Thank you.

So, I will try to go to explain my problem.

**Code**
This is the code I use to create the client. The version this code has some change to no return a timeout exception.

```javascript
	var getId = async function() {
var r = await WA_CLIENT.CONNECTION.sendLinkWithAutoPreview(processData.chatId, BODY['link'], BODY['text']);
console.log(r);
}
getId();
self.json({status:true, id: null});

```
When call in first time, the WhatsApp contact receive the link normally, but, when use a second time not work.
![Anotação 2020-10-10 104943](https://user-images.githubusercontent.com/7800501/95656682-56cd8f00-0ae6-11eb-8dad-0f58c702ec10.png)

The first time recive ack normally
![Anotação 2020-10-10 105043](https://user-images.githubusercontent.com/7800501/95656707-85e40080-0ae6-11eb-9a2d-869c5cb77538.png)

But, on second time, I run like first time, but no more return ack or another exception. This is point stranger.

**Comment by smashah** [comment]
@paulocorcino Try to update your open-wa to the latest version and please give me an example of a link that doesn't work.

**Comment by paulocorcino** [comment]
@smashah I did update, but it continues with the problem. This fail happens with any URL, you can use this as sample https://www.facebook.com/esporteinterativo/. @smashah I did the same routine in another computer (Windows 2012) and receive the same behavior. Can you recommend points where I can make debug?

**Comment by coolgovind** [comment]
I am having this problem from last month and put this in our group too

**Comment by smashah** [comment]
@coolgovind @paulocorcino I'm pretty sure this has been fixed with the latest patch (462fadb) Please restart your sessions and try again. Report back results.

**Comment by paulocorcino** [comment]
@smashah I applaied  the patch but not fixed the fail. Let me show you the sequence of screenhots

This is before send a link.
![vau8bdlfv1_pic1](https://user-images.githubusercontent.com/7800501/95724180-69fa6f00-0c4c-11eb-98ba-4df06ae3610c.png)

I send a simple message
![nvnzp0cl91_pic2](https://user-images.githubusercontent.com/7800501/95724262-88606a80-0c4c-11eb-8a60-2036a5704af1.png)

I send a link with preview, contact received.
![r4d1egj125_pic3](https://user-images.githubusercontent.com/7800501/95724294-94e4c300-0c4c-11eb-9c3e-b8ac225c62eb.png)

Now, when I try send new simple message, show like the message wait for a connection, this behavior happens with any message after send the link
![lz8pyk20t1_pic4](https://user-images.githubusercontent.com/7800501/95724429-bc3b9000-0c4c-11eb-85f6-074ad9e10dac.png)

**Comment by paulocorcino** [comment]
@smashah That's working!!!!

Thankful!!!!
